// ═══════════════════════════════════════════════════════════════
// ZIMONZA — test runner
//
//   node tests/run.mjs            run everything
//   node tests/run.mjs dispatch   run suites matching "dispatch"
//
// The app is a build-less browser app: modules import Firebase and
// PDF.js straight from CDN URLs, which Node cannot resolve. So the
// runner copies js/ into a temp sandbox, rewrites those URLs to local
// stubs, and runs each suite against the copy. The logic under test is
// the real file, byte for byte.
// ═══════════════════════════════════════════════════════════════

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import vm from 'node:vm';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
const sandbox = join(tmpdir(), 'zimonza-tests');

const CDN_REWRITES = [
  [/https:\/\/www\.gstatic\.com\/firebasejs\/[\d.]+\/firebase-[a-z]+\.js/g, './_stub-firebase.js'],
  [/https:\/\/cdn\.jsdelivr\.net\/npm\/pdfjs-dist@[\d.]+\/build\/pdf\.min\.mjs/g, './_stub-pdfjs.js']
];

function build() {
  rmSync(sandbox, { recursive: true, force: true });
  mkdirSync(sandbox, { recursive: true });

  // The app's modules, with CDN imports pointed at stubs
  const names = [];
  for (const f of readdirSync(join(repo, 'js')).filter(f => f.endsWith('.js'))) {
    let src = readFileSync(join(repo, 'js', f), 'utf8');
    for (const [re, to] of CDN_REWRITES) src = src.replace(re, to);
    writeFileSync(join(sandbox, f), src);
    names.push(f);
  }

  // Firebase stub: every named import the repo actually uses
  const imported = new Set();
  for (const f of names) {
    const src = readFileSync(join(repo, 'js', f), 'utf8');
    const re = /import\s*\{([^}]*)\}\s*from\s*['"]https:\/\/www\.gstatic\.com[^'"]*['"]/g;
    let m;
    while ((m = re.exec(src))) {
      m[1].split(',').map(s => s.trim().split(/\s+as\s+/)[0].trim()).filter(Boolean)
        .forEach(n => imported.add(n));
    }
  }
  const special = {
    writeBatch: 'export const writeBatch = () => ({ set(){}, delete(){}, update(){}, commit: async()=>{} });',
    runTransaction: 'export const runTransaction = async (db, fn) => fn({ get: async()=>({ exists:()=>false, data:()=>({}) }), set(){} });',
    getDoc: 'export const getDoc = async () => ({ exists:()=>false, data:()=>({}) });',
    getDocs: 'export const getDocs = async () => ({ docs: [] });',
    serverTimestamp: 'export const serverTimestamp = () => null;'
  };
  writeFileSync(join(sandbox, '_stub-firebase.js'), [
    '// generated by tests/run.mjs',
    'const noop = () => ({});',
    ...Object.values(special),
    ...[...imported].filter(n => !special[n]).map(n => `export const ${n} = noop;`)
  ].join('\n'));

  // Each page is a multi-line string, and every line becomes a POSITIONED
  // text item — y descending down the page, exactly as PDF.js reports it.
  // Without real coordinates a layout-aware reader cannot be tested at all.
  // Tab-separated "x|text" runs place text at a given x on the same line.
  writeFileSync(join(sandbox, '_stub-pdfjs.js'), [
    "export const GlobalWorkerOptions = { workerSrc: '' };",
    'export const Util = { transform: () => [1,0,0,1,0,0] };',
    'const toItems = (page) => {',
    '  if (Array.isArray(page)) return page;',
    '  const out = [];',
    '  String(page ?? "").split(String.fromCharCode(10)).forEach((row, i) => {',
    '    const y = 800 - i * 14;',
    '    for (const run of row.split(String.fromCharCode(9))) {',
    '      const bar = run.indexOf("|");',
    '      const head = bar > 0 ? run.slice(0, bar) : "";',
    '      const numeric = head.length > 0 && !/[^0-9]/.test(head);',
    '      const x = numeric ? Number(head) : 40;',
    '      const str = numeric ? run.slice(bar + 1) : run;',
    '      if (str.trim()) out.push({ str, height: 10, transform: [1,0,0,10,x,y] });',
    '    }',
    '  });',
    '  return out;',
    '};',
    'export const getDocument = () => {',
    '  const pages = globalThis.__PDF_PAGES || [];',
    '  return { promise: Promise.resolve({',
    '    numPages: pages.length,',
    '    getPage: async (n) => ({',
    '      _page: n,',
    '      getTextContent: async () => ({ items: toItems(pages[n - 1]) }),',
    '      getViewport: () => ({ width: 600, height: 900 }),',
    '      render: () => ({ promise: Promise.resolve() })',
    '    })',
    '  }) };',
    '};'
  ].join('\n'));

  // The REAL toast module, kept under another name. The stub below replaces
  // it for every other suite, which would otherwise leave the real one —
  // and its HTML escaping — completely untested.
  cpSync(join(repo, 'js', 'notifications.js'), join(sandbox, '_real-notifications.js'));

  // Toasts must not need a DOM
  writeFileSync(join(sandbox, 'notifications.js'), [
    'const sink = [];',
    'const push = (level) => (msg) => { sink.push(level + ": " + msg); };',
    'const notify = { success: push("success"), error: push("error"),',
    '                 warning: push("warning"), info: push("info"),',
    '                 _sink: sink, _clear: () => { sink.length = 0; } };',
    'export { notify };',
    'export default notify;'
  ].join('\n'));

  // The page-level inline scripts, so their imports are checked too
  for (const page of ['myntra.html', 'pdf-to-excel.html']) {
    const html = readFileSync(join(repo, page), 'utf8');
    const body = html.split('<script type="module">')[1]?.split('</script>')[0] ?? '';
    writeFileSync(join(sandbox, `_page-${page.replace('.html', '')}.txt`), body);
  }

  // The suites
  mkdirSync(join(sandbox, 'suites'), { recursive: true });
  for (const f of readdirSync(here).filter(f => f.endsWith('.test.js'))) {
    cpSync(join(here, f), join(sandbox, f));
  }
  return names;
}

/**
 * Honest syntax check.
 * `node --check` returns exit 0 on files it cannot parse under Node 26 —
 * it accepted a file with `function oops( {` appended. Compiling as an ES
 * module fails properly.
 */
function parseCheck(names) {
  let bad = 0;
  const files = [...names, ...readdirSync(sandbox).filter(f => f.startsWith('_page-'))];
  for (const f of files) {
    const path = join(sandbox, f);
    const src = readFileSync(path, 'utf8');
    try { new vm.SourceTextModule(src, { identifier: f }); }
    catch (e) { bad++; console.log(`  SYNTAX  ${f}: ${e.message.split('\n')[0]}`); }
  }
  return bad;
}

// vm.SourceTextModule needs a flag. Re-exec once with it so the entry
// point stays a plain `node tests/run.mjs`.
if (typeof vm.SourceTextModule !== 'function') {
  const r = spawnSync(process.execPath,
    ['--experimental-vm-modules', fileURLToPath(import.meta.url), ...process.argv.slice(2)],
    { stdio: 'inherit' });
  process.exit(r.status ?? 1);
}

const filter = process.argv[2] || '';
const names = build();

console.log('─'.repeat(64));
let failures = 0;

// Syntax first — a broken file makes every other result meaningless
const syntaxBad = parseCheck(names);
console.log(`${'parse'.padEnd(22)} ${syntaxBad ? 'FAIL' : 'PASS'}  ${names.length} modules + page scripts`);
if (syntaxBad) failures++;

const suites = readdirSync(sandbox).filter(f => f.endsWith('.test.js') && f.includes(filter)).sort();
for (const suite of suites) {
  const r = spawnSync(process.execPath, [join(sandbox, suite)], { encoding: 'utf8' });
  const out = (r.stdout || '') + (r.stderr || '');
  const line = out.split('\n').filter(l => /passed,|clean\.|resolve\./.test(l)).pop() || '';
  const okRun = r.status === 0;
  if (!okRun) {
    failures++;
    // Show the failures themselves, not just the tail — a suite that fails
    // early would otherwise report nothing but its own summary line.
    const lines = out.trim().split('\n');
    const bad = lines.filter(l => /^\s*(FAIL|✗)|Error|error:/i.test(l));
    console.log((bad.length ? bad : lines.slice(-12)).join('\n'));
  }
  console.log(`${suite.replace('.test.js', '').padEnd(22)} ${okRun ? 'PASS' : 'FAIL'}  ${line.trim()}`);
}

console.log('─'.repeat(64));
console.log(failures ? `${failures} failing` : `all green — ${suites.length} suites`);
process.exit(failures ? 1 : 0);
